// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3WMYVLec5zUWzOyq3oGrX-ZUGhbV2Jv8',
    appId: '1:839288325613:web:d79e693e22c6316b3413e4',
    messagingSenderId: '839288325613',
    projectId: 'gymmovil-ce1e1',
    authDomain: 'gymmovil-ce1e1.firebaseapp.com',
    storageBucket: 'gymmovil-ce1e1.firebasestorage.app',
    measurementId: 'G-HBMQ08DVZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjXVNR1i_CAqmOstYyyaCPyjC8d-c-S0E',
    appId: '1:839288325613:android:9cdccfde38c648b53413e4',
    messagingSenderId: '839288325613',
    projectId: 'gymmovil-ce1e1',
    storageBucket: 'gymmovil-ce1e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWl-FuaQ7jLF_uLXQZa8mTrHYLHjthV8',
    appId: '1:839288325613:ios:353d0d802d1f686b3413e4',
    messagingSenderId: '839288325613',
    projectId: 'gymmovil-ce1e1',
    storageBucket: 'gymmovil-ce1e1.firebasestorage.app',
    iosBundleId: 'com.example.gymmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEWl-FuaQ7jLF_uLXQZa8mTrHYLHjthV8',
    appId: '1:839288325613:ios:353d0d802d1f686b3413e4',
    messagingSenderId: '839288325613',
    projectId: 'gymmovil-ce1e1',
    storageBucket: 'gymmovil-ce1e1.firebasestorage.app',
    iosBundleId: 'com.example.gymmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3WMYVLec5zUWzOyq3oGrX-ZUGhbV2Jv8',
    appId: '1:839288325613:web:9a58f2e7637dfbef3413e4',
    messagingSenderId: '839288325613',
    projectId: 'gymmovil-ce1e1',
    authDomain: 'gymmovil-ce1e1.firebaseapp.com',
    storageBucket: 'gymmovil-ce1e1.firebasestorage.app',
    measurementId: 'G-P02ZE1248K',
  );

}